variables:
  AUDIT_AWS_S3_ALERT_LIST:
    description: alert list for generating notifications
    required: true
    type: array
    default:
      - s3-allusers-write
      - s3-allusers-write-acp
      - s3-allusers-read
      - s3-authenticatedusers-write
      - s3-authenticatedusers-write-acp
      - s3-authenticatedusers-read
      - s3-logging-disabled
      - s3-world-open-policy-delete
      - s3-world-open-policy-get
      - s3-world-open-policy-list
      - s3-world-open-policy-put
      - s3-world-open-policy-all
      - s3-only-ip-based-policy
  AUDIT_AWS_S3_ALERT_RECIPIENT:
    description: email recipient for notification
    required: true
    type: string
    default:
  AUDIT_AWS_S3_ALLOW_EMPTY:
    description: receive empty reports?
    required: true
    type: string
    default: false
  AUDIT_AWS_S3_PAYLOAD_TYPE:
    description: json or text
    required: true
    type: string
    default: "json"
  AUDIT_AWS_S3_SEND_ON:
    description: always or change
    required: true
    type: string
    default: "change"
  AUDIT_AWS_S3_REGIONS:
    description: list of AWS regions to check. Default is all regions
    required: true
    type: array
    default:
        - us-east-1
        - us-west-1
        - us-west-2
#       - ap-south-1
#       - ap-northeast-1
#       - ap-northeast-2
#       - ap-southeast-1
#       - ap-southeast-2
#       - eu-central-1
#       - eu-west-1
#       - sa-east-1
